spring.application.name=scrapper

spring.datasource.url=jdbc:postgresql://localhost:5432/webscraper
spring.datasource.username=postgres
spring.datasource.password=dbpw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false